### ISSUE TITLE
Problem with error message to load

### ISSUE THREAD

**Issue by Raphy123** [SBPrime/AsyncWorldEdit-Premium#158] opened 2019-01-02 20:04 UTC
Hi

I have this error message when I load : [

20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * CLASS INJECTION FAILED!! *
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] ****************************
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * AsyncWorldEdit won't work properly.
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] *
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * Exception: java.lang.ClassFormatError
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * Error message: Unable to invoke dynamic method. loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate cla$
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * Stack:
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.ClassInjectorBukkit.injectClass(ClassInjectorBukkit.java:119)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.modiffyClasses(InjectorCore.java:260)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.core.InjectorCore.initialize(InjectorCore.java:173)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.InjectorBukkit.onEnable(InjectorBukkit.java:89)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.AsyncWorldEditBukkit.onLoad(AsyncWorldEditBukkit.java:248)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:328)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:748)
[20:58:16] [Server thread/INFO]: [AsyncWorldEdit] ****************************
I have worldedit beta 3
I have worldguard

Regards,

**Comment by SBPrime** [comment] 2019-01-07 09:57
Is this error caused by P2?

**Comment by SBPrime** [comment] 2019-01-08 21:19
Fixed in rc04

**Closed as completed by SBPrime** 2019-01-08 21:19 UTC
