### ISSUE TITLE
/chunk relight not working anymore?

### ISSUE THREAD

**Issue by leasoncre** [SBPrime/AsyncWorldEdit-Premium#22] opened 2015-10-28 00:54 UTC
v3.2.2
i remember using this command in 3.1.1 [inside a selection box] and it appeared to place blocks [though invisible to me] as i watched it progress. now it just instant-.... does nothing..
at least nothing i can discern. relog doesn't update it. repeating the command does nothing.

pasted some schematics but a bunch of the light source blocks didn't update so the whole cavern is pretty much dark now.

i know this used to work. idk why it's not anymore. 
https://gyazo.com/dffa8b6c77c77b92c61c3cfceb0b483e [any vertical trapdoor has glowstone behind it, you can see some of them have barely any light around them]

**Comment by leasoncre** [comment] 2015-10-28 00:58
replaced all the glowstone with another block then undid it. and things re-lit fine

**Comment by SBPrime** [comment] 2015-10-28 05:08
Since 3.1.1 no changes ware made to the relight command. I'll check this and get back to you.

**Comment by SBPrime** [comment] 2015-12-28 16:29
I'm unable to reproduce this issue. The whole problem might be a minor misunderstanding how the direct chunk API works.

To improve performance I disabled relight calculation in DC mode. So for example if you do /chunk paste it wont relight the area. You need to do manually /chunk relight (select the chunk first!) or you can do /chunk paste -l. If you don't have any more to add regarding this issue I'll be force to close it as "works for me".

**Comment by leasoncre** [comment] 2015-12-30 22:05
i have no idea why it works on your server. but it still doesn't work on mine. (did what ya said, exactly)

i'm thinking there might be a lighting glitch bug with minecraft/mojang/spigot. but i really have no clue.

Async 3.2.3 (with blockshub-coreprotect)
git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

aside from coming on the server i run this on, i have no idea what else to tell ya.

**Comment by SBPrime** [comment] 2015-12-31 10:24
Could you try it on a clean server? (only WE + AWE). It would also help if you provided startup log + debug output (turn it on in the config) when you did the relight command

**Comment by leasoncre** [comment] 2016-01-01 14:45
tested on fresh server. awe debug on.
pasted part of (server decided to crash me after pasting about 1/3 of it, default awe config) a big schematic for testing this
log: http://pastebin.com/JC5XAvy1 [line 525 for /chunk relight command]
[screenshot of after: https://gyazo.com/e69040c93457cc79d6ac48dcc54eab60 ]

**Comment by SBPrime** [comment] 2016-05-02 14:11
Any update?

**Closed as completed** 2016-05-05 04:44 UTC
