### ISSUE TITLE
Plugin conflict causes ClassCastException on //undo

### ISSUE THREAD

**Issue by NLthijs48** [SBPrime/AsyncWorldEdit-Premium#107] opened 2016-10-17 20:48 UTC
There was an error when I attempted to undo a `//set` of a big block of stone, any idea what this is caused by or how to fix it?

Startup and error log: http://pastebin.com/6E9g3K4j

**Versions:**
- Spigot: CraftBukkit version git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
- AsyncWorldEdit Premium: 3.4.4 (stroudje is the buyer of the plugin, running the server together)
- WorldEdit: 6.1.4 (build 3595 from http://builds.enginehub.org/job/worldedit?branch=master)

**Comment by SBPrime** [comment] 2016-10-18 13:22
Send the server log when the error occurs but please enable debug mode in AWE. This is most likely some plugin conflict. I tested this using the latest spigot + AWE + WE that you specified.

**Comment by NLthijs48** [comment] 2016-10-18 14:30
I enabled the debug setting and did my test again, this is the result:
http://mc.go-craft.com/STORAGE/withDebug.txt

First I select a big chunk, then set it to stone, which works correctly. Then I use `//undo`, which also works correctly. Then I fly away from the area I have the selection (chunks probably unload at that point), then I use `//set stone` again, which tells the block bag and undo is broken (and does nothing, selected area stays air).

The config I use is this: http://pastebin.com/C99c9jAS I'm in the staff group and therefore have relaxed limits compared to default players.

BlocksHub V2.0.1 is installed, and I'm WorldEditing inside a plot of PlotSquared 3.4.6.

**Comment by SBPrime** [comment] 2016-10-18 16:11
Something is wrong with your setup. Basically when your edit session is created the world argument is null.

The first operation:

```
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] * Found EditSession
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] -----------------------
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] Original extents:
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.plotsquared.listener.ProcessedWEExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.validation.BlockChangeLimiter
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.MaskingExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.ChangeSetExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.plotsquared.listener.ProcessedWEExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.reorder.MultiStageReorder
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.inventory.BlockBagExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.validation.DataValidatorExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.plotsquared.listener.ProcessedWEExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.cache.LastAccessExtentCache
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.world.ChunkLoadingExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.world.BlockQuirkExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.world.SurvivalModeExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.world.FastModeExtent
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] ...org.primesoft.asyncworldedit.worldedit.world.CancelableWorld
[15:34:36] [Server thread/INFO]: [AsyncWorldEdit] -----------------------
```

The second operation:

```
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] ****************************************************************
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] * Validating scann results
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] ****************************************************************
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] * Found EditSession
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] -----------------------
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] Original extents:
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.NullExtent
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] -----------------------
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] Unable to get the blockBagExtent from EditSession, block bag broken.
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] Unable to get the changesetExtent from EditSession, undo broken.
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] -----------------------
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] Injected extents:
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] ...com.sk89q.worldedit.extent.NullExtent
[15:35:28] [Server thread/INFO]: [AsyncWorldEdit] -----------------------
```

In WorldEdit the NullExtent is created only when you use null as the world. I would assume that this might be caused by the PlotSquered WorldEdit integration. 

In PlotSquered:
https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/plotsquared/listener/WESubscriber.java#L47
https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/plotsquared/listener/WESubscriber.java#L60

It sets NullExtent as the extent and this causes WorldEdit to disable all edits in the EditSession.

I'll try to add a workaround for this.

**Comment by SBPrime** [comment] 2016-10-18 16:27
Fixed in 3.4.5

**Closed as completed by SBPrime** 2016-10-18 16:27 UTC

**Comment by NLthijs48** [comment] 2016-10-18 16:37
Thanks for the quick workaround! Installing the update immediately :)

What kind of Extent should have been used in PlotSquared? Because it might be useful to tell the developer of PlotSquared, or even make a pull request to change it.

**Comment by SBPrime** [comment] 2016-10-18 18:01
Actually this is not an error. PS uses the NullExtent to disable all world edit in an area that you should not be able to use it (if its done correctly that's a completely different story. I don't know it might be done correctly might not). That's the easiest way to do it, and I probably would do it the same way.
