### ISSUE TITLE
//replace sign air server freeze

### ISSUE THREAD

**Issue by andris155** [SBPrime/AsyncWorldEdit-Premium#169] opened 2019-03-04 13:49 UTC
```
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] -----------------------------------------------------------------------
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] Warning: Class scanner encountered an error while scanning class
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] Exception: java.lang.OutOfMemoryError, Java heap space
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/java.util.Arrays.copyOf(Arrays.java:3689)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/java.util.ArrayDeque.grow(ArrayDeque.java:150)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:308)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.scanner.ClassScanner.scan(ClassScanner.java:213)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:128)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethodEx(Helpers.java:90)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.EditSession.replaceBlocks(EditSession.java:994)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.worldedit.AsyncEditSession.replaceBlocks(AsyncEditSession.java:985)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.command.RegionCommands.replace(RegionCommands.java:167)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.primesoft.asyncworldedit.worldedit.util.command.DispatcherWrapper.call(DispatcherWrapper.java:211)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:275)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] jdk.internal.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:218)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605)
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] Class: class java.util.HashMap
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] Object: {minecraft:sign=java.lang.Object@b702db0}
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] Send this message to the author of the plugin!
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] https://github.com/SBPrime/AsyncWorldEdit/issues
[14:43:50] [Server thread/INFO]: [AsyncWorldEdit] -----------------------------------------------------------------------
```

**Comment by SBPrime** [comment] 2019-03-05 20:14
Please enable debug mode, try to perform the operation and send me the log (at leas firs ~100 lines after starting the operation). This is most likely caused by a third party plugin.

**Comment by SBPrime** [comment] 2019-05-20 11:55
No update, closing the issue.

**Closed as completed by SBPrime** 2019-05-20 11:55 UTC
