### ISSUE TITLE
//br forest does not create trees

### ISSUE THREAD

**Issue by LauJosefsen** [SBPrime/AsyncWorldEdit-Premium#193] opened 2019-09-06 19:21 UTC
Hi.

I am running a server with the current setup:
WorldEdit: 7.0.1;61bc012
AsyncWorldEdit 3.6.10
Paper #171

Whenever i use the //br forest command, i cannot get it working with ASWE enabled. It changes some things, like tallgrass, but does not plant the trees.  ""/awe toggle" will make it work.

**Comment by SBPrime** [comment] 2019-10-27 08:20
Duplicate of: https://github.com/SBPrime/AsyncWorldEdit/issues/213
Unfortunately the fix is not that straight forward.

**Closed as completed by SBPrime** 2019-10-27 08:20 UTC
