### ISSUE TITLE
//move randomly lost blocks

### ISSUE THREAD

**Issue by jessefjxm** [SBPrime/AsyncWorldEdit-Premium#93] opened 2016-08-01 08:57 UTC
Found a severe bug of AWE 3.4.0, working with WE 6.1.3 in Spigot 1.8.9. When moving, blocks will randomly disappear, without any warning. I roll back to 3.3.12 and the problem gone. Hope it can be fixed soon.

**Comment by manuelgu** [comment] 2016-08-01 09:44
Duplicate of #88

**Closed as completed** 2016-08-01 16:21 UTC
