### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mibby** [SBPrime/AsyncWorldEdit-Premium#66] opened 2016-05-17 05:34 UTC
AsyncWorldEdit Premium 3.3.8

Command used before the error occurred.

```
[12:05:54] [Server thread/INFO]: WorldEdit: player (in "world"): /replace air 99.9%air,0.1%wood:5 - Region: (-11155.0, 20.0, 11297.0) - (-11125.0, 37.0, 11329.0)
```

```
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] ***********************************
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] Error performing safe operation for world cx: -696 cz: 706 Loaded: true, inUse: true
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] ***********************************
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * Exception: java.lang.IndexOutOfBoundsException
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * Error message: Index: 64, Size: 0
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * Stack: 
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * java.util.ArrayList.rangeCheck(ArrayList.java:653)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * java.util.ArrayList.get(ArrayList.java:429)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_9_R2.World.F(World.java:2095)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_9_R2.World.getTileEntity(World.java:2085)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * net.minecraft.server.v1_9_R2.WorldServer.getTileEntity(WorldServer.java:127)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_9_R2.getBlock(Spigot_v1_9_R2.java:213)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:405)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$37.execute(AsyncWorld.java:954)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$37.execute(AsyncWorld.java:951)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:563)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getBlock(AsyncWorld.java:951)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.EditSession.getBlock(EditSession.java:416)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doGetBlock(ThreadSafeEditSession.java:909)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.access$000(ThreadSafeEditSession.java:115)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession$2.execute(ThreadSafeEditSession.java:550)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession$2.execute(ThreadSafeEditSession.java:547)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:563)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.getBlock(ThreadSafeEditSession.java:547)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.CancelabeEditSession.getBlock(CancelabeEditSession.java:244)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.mask.BlockMask.test(BlockMask.java:97)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.sk89q.worldedit.function.operation.Operations$2.Execute(Operations.java:69)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.injector.async.AsyncOperationProcessor$1.task(AsyncOperationProcessor.java:154)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.AsyncTask.doRun(AsyncTask.java:64)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.primesoft.asyncworldedit.worldedit.BaseTask.run(BaseTask.java:142)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] * java.lang.Thread.run(Thread.java:745)
[12:05:54] [Craft Scheduler Thread - 137/INFO]: [AsyncWorldEdit] ***********************************
```

**Comment by SBPrime** [comment] 2016-05-17 16:35
Duplicate of #1

**Closed as completed by SBPrime** 2016-05-17 16:35 UTC
