### ISSUE TITLE
Unable to be used with WorldEdit DEV (b3437) in Spigot 1.9

### ISSUE THREAD

**Issue by PikachuEXE** [SBPrime/AsyncWorldEdit-Premium#41] opened 2016-03-08 12:50 UTC
I just paid for this plugin yesterday. Thanks for your hardwork!
But I am unable to use the DEV version with WorldEdit's DEV version
# Env

Minecraft: "CraftBukkit version git-Spigot-3104eb1-bf43ca6 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)"
Worldedit: b3437 (http://builds.enginehub.org/job/worldedit/8533)
AWE: https://www.spigotmc.org/resources/asyncworldedit-premium.9661/update?update=72824
# Log

```
[20:44:52] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.1-SNAPSHOT;3437-c6b4772
[20:44:52] [Server thread/ERROR]: Error occurred while enabling WorldEdit v6.1.1-SNAPSHOT;3437-c6b4772 (Is it up to date?)
java.lang.ExceptionInInitializerError
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:98) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: Replacing commands is currently undefined behavior
    at com.sk89q.worldedit.util.command.SimpleDispatcher.registerCommand(SimpleDispatcher.java:64) ~[?:?]
    at com.sk89q.worldedit.util.command.fluent.DispatcherNode.register(DispatcherNode.java:71) ~[?:?]
    at com.sk89q.worldedit.extension.platform.CommandManager.<init>(CommandManager.java:153) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:86) ~[?:?]
    at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:95) ~[?:?]
    at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:91) ~[?:?]
    ... 12 more
[20:44:52] [Server thread/INFO]: [AsyncWorldEdit] Initializing WorldEdit.
[20:44:52] [Server thread/ERROR]: Could not pass event PluginEnableEvent to AsyncWorldEdit v3.3.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.getWorldEdit(WorldEditPlugin.java:391) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.WorldeditIntegrator.<init>(WorldeditIntegrator.java:115) ~[?:?]
    at org.primesoft.asyncworldedit.core.AsyncWorldEditCore.initializeWorldEdit(AsyncWorldEditCore.java:311) ~[?:?]
    at org.primesoft.asyncworldedit.AsyncWorldEditMain.onPluginEnabled(AsyncWorldEditMain.java:324) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9-b665.jar:git-Spigot-3104eb1-bf43ca6]
    ... 13 more
```

**Comment by SBPrime** [comment] 2016-03-08 17:16
Duplicate of #40, please look for solution there.

**Closed as completed by SBPrime** 2016-03-08 17:16 UTC
